/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 gru.glb -T -S
Author: anhto (https://sketchfab.com/anhto)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gru-gru-649625f4fa7b4928a464d3e0ce737cb2
Title: Gru Gru
*/

import { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Gru(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/gru-transformed.glb");
  const animation = useAnimations(animations, group);

  useEffect(() => {
    const action = animation.actions["Take 001"];

    action.play();
  }, []);
  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      scale={0.05}
      position={[0, 0, 2]}
    >
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="grugrufbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <primitive object={nodes._rootJoint} />
                  {/* <group name="pSphere1" scale={115.45}>
                    <mesh
                      name="pSphere1_lambert4_0"
                      geometry={nodes.pSphere1_lambert4_0.geometry}
                      material={materials.lambert4}
                    />
                  </group> */}
                  <skinnedMesh
                    name="Object_7"
                    geometry={nodes.Object_7.geometry}
                    material={materials.lambert3}
                    skeleton={nodes.Object_7.skeleton}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/gru-transformed.glb");
