/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 house.glb -T -S
Author: Bogdan Streletskiy (https://sketchfab.com/streletskiy)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/house-on-lake-150b3f1249874c049bcb9c5915cc0409
Title: House on Lake
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function House(props) {
  const { nodes, materials } = useGLTF("/house-transformed.glb");
  return (
    <group
      {...props}
      dispose={null}
      rotation={[0, -Math.PI, 0]}
      position={[0, -6, 0]}
      scale={0.02}
    >
      <group scale={0.1}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.ground_ground_top_0.geometry}
            material={materials.ground_top}
          />
          <mesh
            geometry={nodes.ground_ground_side_0.geometry}
            material={materials.ground_side}
          />
          <mesh
            geometry={nodes.ground_ground_bottom_0.geometry}
            material={materials.ground_bottom}
          />
          <mesh
            geometry={nodes.ground_water_0.geometry}
            material={materials.water}
          />
        </group>
        <group
          position={[-8612.69, -50, -11194.07]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={1.4}
        >
          <mesh
            geometry={nodes.tree_001_tree_wood_0.geometry}
            material={materials.tree_wood}
          />
          <mesh
            geometry={nodes.tree_001_tree_leaves_2_0.geometry}
            material={materials.tree_leaves_2}
          />
        </group>
        <group
          position={[-10202.17, -222.9, -4306.36]}
          rotation={[-1.62, -0.02, -0.1]}
          scale={0.65}
        >
          <mesh
            geometry={nodes.tree_002_tree_wood_0.geometry}
            material={materials.tree_wood}
          />
          <mesh
            geometry={nodes.tree_002_tree_leaves_1_0.geometry}
            material={materials.tree_leaves_1}
          />
        </group>
        <group
          position={[11022.29, -448.34, 23940.11]}
          rotation={[-1.65, -0.02, 1.06]}
          scale={0.6}
        >
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_001_tree_wood_0.geometry
            }
            material={materials.tree_wood}
          />
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_001_tree_leaves_1_0.geometry
            }
            material={materials.tree_leaves_1}
          />
        </group>
        <group
          position={[20450.46, 3895.49, -11647.09]}
          rotation={[-1.48, -0.1, -2.92]}
          scale={0.76}
        >
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_002_tree_wood_0.geometry
            }
            material={materials.tree_wood}
          />
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_002_tree_leaves_2_0.geometry
            }
            material={materials.tree_leaves_2}
          />
        </group>
        <group
          position={[-2210.35, 507.32, -17225.14]}
          rotation={[-1.3, 0.03, -0.65]}
          scale={0.39}
        >
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_003_tree_wood_0.geometry
            }
            material={materials.tree_wood}
          />
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_003_tree_leaves_1_0.geometry
            }
            material={materials.tree_leaves_1}
          />
        </group>
        <group
          position={[-13162.01, 2790.39, -18865.96]}
          rotation={[-1.38, 0.08, -2.53]}
          scale={0.71}
        >
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_004_tree_wood_0.geometry
            }
            material={materials.tree_wood}
          />
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_004_tree_leaves_1_0.geometry
            }
            material={materials.tree_leaves_1}
          />
        </group>
        <group
          position={[15458.87, 1737.8, -13199.94]}
          rotation={[-1.39, -0.08, 2]}
          scale={1.08}
        >
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_005_tree_wood_0.geometry
            }
            material={materials.tree_wood}
          />
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_005_tree_leaves_1_0.geometry
            }
            material={materials.tree_leaves_1}
          />
        </group>
        <group
          position={[-4577.76, 4706.81, -26215.02]}
          rotation={[-1.38, 0.21, -0.23]}
          scale={0.59}
        >
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_006_tree_wood_0.geometry
            }
            material={materials.tree_wood}
          />
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_006_tree_leaves_1_0.geometry
            }
            material={materials.tree_leaves_1}
          />
        </group>
        <group
          position={[25344.25, 4377.5, -1437.28]}
          rotation={[-1.54, -0.01, -2.51]}
          scale={0.76}
        >
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_008_tree_wood_0.geometry
            }
            material={materials.tree_wood}
          />
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_008_tree_leaves_3_0.geometry
            }
            material={materials.tree_leaves_3}
          />
        </group>
        <group
          position={[-9402.27, 6004.4, -26639.41]}
          rotation={[-1.69, 0.13, 0.21]}
          scale={0.98}
        >
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_010_tree_wood_0.geometry
            }
            material={materials.tree_wood}
          />
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_010_tree_leaves_2_0.geometry
            }
            material={materials.tree_leaves_2}
          />
        </group>
        <group
          position={[18601.99, 794.99, 3027.9]}
          rotation={[-1.57, -0.04, 0.71]}
          scale={1.09}
        >
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_012_tree_wood_0.geometry
            }
            material={materials.tree_wood}
          />
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_012_tree_leaves_1_0.geometry
            }
            material={materials.tree_leaves_1}
          />
        </group>
        <group
          position={[-27123.85, -50, 13911.2]}
          rotation={[-1.6, 0.05, -2.61]}
          scale={0.83}
        >
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_013_tree_wood_0.geometry
            }
            material={materials.tree_wood}
          />
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_013_tree_leaves_3_0.geometry
            }
            material={materials.tree_leaves_3}
          />
        </group>
        <group
          position={[7691.8, -186.98, 27751.9]}
          rotation={[-1.62, 0.05, -1.34]}
          scale={0.48}
        >
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_014_tree_wood_0.geometry
            }
            material={materials.tree_wood}
          />
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_014_tree_leaves_2_0.geometry
            }
            material={materials.tree_leaves_2}
          />
        </group>
        <group
          position={[18390.56, -78.13, 21093.14]}
          rotation={[-1.61, -0.07, 2.47]}
          scale={1.05}
        >
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_015_tree_wood_0.geometry
            }
            material={materials.tree_wood}
          />
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_015_tree_leaves_2_0.geometry
            }
            material={materials.tree_leaves_2}
          />
        </group>
        <group
          position={[-21769.81, 928.25, -7702.36]}
          rotation={[-1.44, 0.06, 2.52]}
          scale={0.48}
        >
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_016_tree_wood_0.geometry
            }
            material={materials.tree_wood}
          />
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_016_tree_leaves_3_0.geometry
            }
            material={materials.tree_leaves_3}
          />
        </group>
        <group
          position={[20755.19, 6897.23, -17687.33]}
          rotation={[-1.5, -0.02, 0.21]}
          scale={1.58}
        >
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_017_tree_wood_0.geometry
            }
            material={materials.tree_wood}
          />
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_017_tree_leaves_3_0.geometry
            }
            material={materials.tree_leaves_3}
          />
        </group>
        <group
          position={[2445.42, 3304.03, -24337.29]}
          rotation={[-1.43, 0.05, 1.79]}
          scale={1.62}
        >
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_018_tree_wood_0.geometry
            }
            material={materials.tree_wood}
          />
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_018_tree_leaves_1_0.geometry
            }
            material={materials.tree_leaves_1}
          />
        </group>
        <group
          position={[2198.4, -50, -11160.29]}
          rotation={[-1.62, 0.02, -1.17]}
          scale={0.95}
        >
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_020_tree_wood_0.geometry
            }
            material={materials.tree_wood}
          />
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_020_tree_leaves_2_0.geometry
            }
            material={materials.tree_leaves_2}
          />
        </group>
        <group
          position={[-2875.37, -136.28, -5473.37]}
          rotation={[-1.6, 0.01, -1.03]}
          scale={0.66}
        >
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_021_tree_wood_0.geometry
            }
            material={materials.tree_wood}
          />
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_021_tree_leaves_1_0.geometry
            }
            material={materials.tree_leaves_1}
          />
        </group>
        <group
          position={[25206.07, 3556.77, 5413.58]}
          rotation={[-1.48, -0.1, 0.77]}
          scale={1.24}
        >
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_022_tree_wood_0.geometry
            }
            material={materials.tree_wood}
          />
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_022_tree_leaves_2_0.geometry
            }
            material={materials.tree_leaves_2}
          />
        </group>
        <group
          position={[12299.66, -49.81, -2422.57]}
          rotation={[-1.49, -0.02, 0.94]}
          scale={0.5}
        >
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_023_tree_wood_0.geometry
            }
            material={materials.tree_wood}
          />
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_023_tree_leaves_2_0.geometry
            }
            material={materials.tree_leaves_2}
          />
        </group>
        <group
          position={[-29217.14, 563.47, -5030.51]}
          rotation={[-1.53, -0.05, 0.52]}
          scale={0.47}
        >
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_025_tree_wood_0.geometry
            }
            material={materials.tree_wood}
          />
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_025_tree_leaves_1_0.geometry
            }
            material={materials.tree_leaves_1}
          />
        </group>
        <group
          position={[28075.36, 5315.43, -9691.87]}
          rotation={[-1.57, 0.02, -0.36]}
          scale={1.16}
        >
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_026_tree_wood_0.geometry
            }
            material={materials.tree_wood}
          />
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_026_tree_leaves_1_0.geometry
            }
            material={materials.tree_leaves_1}
          />
        </group>
        <group
          position={[11820.17, 3732.23, -20804.22]}
          rotation={[-1.29, -0.08, -0.26]}
          scale={1.64}
        >
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_027_tree_wood_0.geometry
            }
            material={materials.tree_wood}
          />
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_027_tree_leaves_2_0.geometry
            }
            material={materials.tree_leaves_2}
          />
        </group>
        <group
          position={[18127.68, 1262.44, -6763.59]}
          rotation={[-1.5, -0.02, -2.99]}
          scale={0.69}
        >
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_029_tree_wood_0.geometry
            }
            material={materials.tree_wood}
          />
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_029_tree_leaves_2_0.geometry
            }
            material={materials.tree_leaves_2}
          />
        </group>
        <group
          position={[-13857.94, 5799.26, -24377.72]}
          rotation={[-1.46, 0.11, -2.47]}
          scale={0.48}
        >
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_031_tree_wood_0.geometry
            }
            material={materials.tree_wood}
          />
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_031_tree_leaves_1_0.geometry
            }
            material={materials.tree_leaves_1}
          />
        </group>
        <group
          position={[18388.48, 927.61, -2650.69]}
          rotation={[-1.61, -0.11, -1]}
          scale={0.45}
        >
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_032_tree_wood_0.geometry
            }
            material={materials.tree_wood}
          />
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_032_tree_leaves_1_0.geometry
            }
            material={materials.tree_leaves_1}
          />
        </group>
        <group
          position={[-24872.63, -69.44, 4758.97]}
          rotation={[-1.55, 0.02, 2.63]}
          scale={0.8}
        >
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_034_tree_wood_0.geometry
            }
            material={materials.tree_wood}
          />
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_034_tree_leaves_2_0.geometry
            }
            material={materials.tree_leaves_2}
          />
        </group>
        <group
          position={[-16370.84, 489.73, -8273.12]}
          rotation={[-1.5, 0.06, 1.66]}
          scale={1.01}
        >
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_036_tree_wood_0.geometry
            }
            material={materials.tree_wood}
          />
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_036_tree_leaves_1_0.geometry
            }
            material={materials.tree_leaves_1}
          />
        </group>
        <group
          position={[14137.52, 83.52, -5468.17]}
          rotation={[-1.5, -0.03, 0.76]}
          scale={0.7}
        >
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_037_tree_wood_0.geometry
            }
            material={materials.tree_wood}
          />
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_037_tree_leaves_3_0.geometry
            }
            material={materials.tree_leaves_3}
          />
        </group>
        <group
          position={[-23797.6, 4151.79, -15560.58]}
          rotation={[-1.4, 0.11, -2.88]}
          scale={0.45}
        >
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_040_tree_wood_0.geometry
            }
            material={materials.tree_wood}
          />
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_040_tree_leaves_1_0.geometry
            }
            material={materials.tree_leaves_1}
          />
        </group>
        <group
          position={[-21497.67, -319.11, 10034.81]}
          rotation={[-1.62, -0.01, -0.67]}
          scale={0.62}
        >
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_041_tree_wood_0.geometry
            }
            material={materials.tree_wood}
          />
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_041_tree_leaves_1_0.geometry
            }
            material={materials.tree_leaves_1}
          />
        </group>
        <group
          position={[-21826.21, -151.41, -2417.43]}
          rotation={[-1.49, 0.06, -2.91]}
          scale={1.01}
        >
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_042_tree_wood_0.geometry
            }
            material={materials.tree_wood}
          />
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_042_tree_leaves_1_0.geometry
            }
            material={materials.tree_leaves_1}
          />
        </group>
        <group
          position={[6692.94, 587.24, -16484.81]}
          rotation={[-1.46, 0.07, -2.73]}
          scale={0.49}
        >
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_046_tree_wood_0.geometry
            }
            material={materials.tree_wood}
          />
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_046_tree_leaves_1_0.geometry
            }
            material={materials.tree_leaves_1}
          />
        </group>
        <group
          position={[22249.62, 3046.15, -4950.19]}
          rotation={[-1.55, -0.03, -2.92]}
          scale={0.52}
        >
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_047_tree_wood_0.geometry
            }
            material={materials.tree_wood}
          />
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_047_tree_leaves_1_0.geometry
            }
            material={materials.tree_leaves_1}
          />
        </group>
        <group
          position={[-24651.38, 2051, -10755.36]}
          rotation={[-1.48, -0.08, 0.7]}
          scale={0.28}
        >
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_048_tree_wood_0.geometry
            }
            material={materials.tree_wood}
          />
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_048_tree_leaves_1_0.geometry
            }
            material={materials.tree_leaves_1}
          />
        </group>
        <group
          position={[21505.54, 48.5, 13216.83]}
          rotation={[-1.59, -0.08, -0.22]}
          scale={0.78}
        >
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_049_tree_wood_0.geometry
            }
            material={materials.tree_wood}
          />
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_049_tree_leaves_1_0.geometry
            }
            material={materials.tree_leaves_1}
          />
        </group>
        <group
          position={[-19470.39, 5046.94, -20557.07]}
          rotation={[-1.38, 0.07, 2.42]}
          scale={0.98}
        >
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_051_tree_wood_0.geometry
            }
            material={materials.tree_wood}
          />
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_051_tree_leaves_3_0.geometry
            }
            material={materials.tree_leaves_3}
          />
        </group>
        <group
          position={[12272.04, -310.19, 3988.49]}
          rotation={[-1.57, -0.05, 0.42]}
          scale={0.4}
        >
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_052_tree_wood_0.geometry
            }
            material={materials.tree_wood}
          />
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_052_tree_leaves_3_0.geometry
            }
            material={materials.tree_leaves_3}
          />
        </group>
        <group
          position={[26815.9, 2414.38, 10749.45]}
          rotation={[-1.32, 0.04, -0.88]}
          scale={0.79}
        >
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_059_tree_wood_0.geometry
            }
            material={materials.tree_wood}
          />
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_059_tree_leaves_3_0.geometry
            }
            material={materials.tree_leaves_3}
          />
        </group>
        <group
          position={[-5893.66, 2393.92, -21050.39]}
          rotation={[-1.29, 0.09, -3.14]}
          scale={1.13}
        >
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_060_tree_wood_0.geometry
            }
            material={materials.tree_wood}
          />
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_060_tree_leaves_3_0.geometry
            }
            material={materials.tree_leaves_3}
          />
        </group>
        <group
          position={[-19233.44, 2546.23, -13747.75]}
          rotation={[-1.58, 0.06, -0.54]}
          scale={0.56}
        >
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_062_tree_wood_0.geometry
            }
            material={materials.tree_wood}
          />
          <mesh
            geometry={
              nodes.CoronaScatter_converted_tree_062_tree_leaves_2_0.geometry
            }
            material={materials.tree_leaves_2}
          />
        </group>
        <group
          position={[8393.01, -132.32, -7101.43]}
          rotation={[-Math.PI / 2, 0, -0.61]}
        >
          <group position={[0, 0, 500]}>
            <mesh
              geometry={nodes.house_roof_top_0.geometry}
              material={materials.roof_top}
            />
            <mesh
              geometry={nodes.house_white_0.geometry}
              material={materials.white}
            />
            <mesh
              geometry={nodes.house_walls_0.geometry}
              material={materials.walls}
            />
            <mesh
              geometry={nodes.house_roof_sides_0.geometry}
              material={materials.roof_sides}
            />
          </group>
          <group position={[-2300, -1000, 600]} rotation={[0, 0, Math.PI]}>
            <mesh
              geometry={nodes.Box014_white_0.geometry}
              material={materials.white}
            />
            <mesh
              geometry={nodes.Box014_glass_0.geometry}
              material={materials.glass}
            />
          </group>
          <group
            position={[0, -3100, 4324.42]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[1.37, 1.37, 1]}
          >
            <mesh
              geometry={nodes.Cylinder001_white_0.geometry}
              material={materials.white}
            />
            <mesh
              geometry={nodes.Cylinder001_glass_0.geometry}
              material={materials.glass}
            />
          </group>
          <group position={[-1250, -3050, 600]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh
              geometry={nodes.Box005_white_0.geometry}
              material={materials.white}
            />
            <mesh
              geometry={nodes.Box005_glass_0.geometry}
              material={materials.glass}
            />
          </group>
          <group position={[1250, -3050, 600]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh
              geometry={nodes.Box006_white_0.geometry}
              material={materials.white}
            />
            <mesh
              geometry={nodes.Box006_glass_0.geometry}
              material={materials.glass}
            />
          </group>
          <group position={[0, -3050, 600]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh
              geometry={nodes.Box009_white_0.geometry}
              material={materials.white}
            />
            <mesh
              geometry={nodes.Box009_door_0.geometry}
              material={materials.door}
            />
          </group>
          <group
            position={[-1250, 3050, 600]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={[-1, 1, 1]}
          >
            <mesh
              geometry={nodes.Box010_white_0.geometry}
              material={materials.white}
            />
            <mesh
              geometry={nodes.Box010_glass_0.geometry}
              material={materials.glass}
            />
          </group>
          <group
            position={[1250, 3050, 600]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={[-1, 1, 1]}
          >
            <mesh
              geometry={nodes.Box011_white_0.geometry}
              material={materials.white}
            />
            <mesh
              geometry={nodes.Box011_glass_0.geometry}
              material={materials.glass}
            />
          </group>
          <group position={[2300, -1000, 600]}>
            <mesh
              geometry={nodes.Box012_white_0.geometry}
              material={materials.white}
            />
            <mesh
              geometry={nodes.Box012_glass_0.geometry}
              material={materials.glass}
            />
          </group>
          <group position={[2300, 1000, 600]}>
            <mesh
              geometry={nodes.Box013_white_0.geometry}
              material={materials.white}
            />
            <mesh
              geometry={nodes.Box013_glass_0.geometry}
              material={materials.glass}
            />
          </group>
          <group position={[-2300, 1000, 600]} rotation={[0, 0, Math.PI]}>
            <mesh
              geometry={nodes.Box015_white_0.geometry}
              material={materials.white}
            />
            <mesh
              geometry={nodes.Box015_glass_0.geometry}
              material={materials.glass}
            />
          </group>
        </group>
        <group
          position={[6712.89, -112.61, 1915.76]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 3]}
        >
          <mesh
            geometry={nodes.marine_wood_planks_0.geometry}
            material={materials.wood_planks}
          />
          <mesh
            geometry={nodes.marine_tree_wood_0.geometry}
            material={materials.tree_wood}
          />
        </group>
        <group
          position={[4098.45, -112.61, 3735.12]}
          rotation={[0, Math.PI / 6, 0]}
          scale={1.2}
        >
          <mesh
            geometry={nodes.char_man_char_man_0.geometry}
            material={materials.char_man}
            position={[-567.78, 112.61, 449.17]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 6]}
          />
        </group>
        <mesh
          geometry={nodes.smoke_smoke_0.geometry}
          material={materials.smoke}
          position={[8585.37, 10294.62, -4866.74]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes.CoronaScatter_converted_grass_001_grass_0.geometry}
          material={materials.grass}
          position={[11024.17, -448.15, 23942.96]}
          rotation={[-1.65, -0.13, 1.07]}
          scale={1.75}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/house-transformed.glb");
